### ISSUE TITLE
latest pull from kkaempf/LibLaserCut causes a Java Exception

### ISSUE THREAD

**Issue by jnweiger** [fablabnbg/VisiCut#16]
Tested https://github.com/fablabnbg/VisiCut/releases/tag/v1.7-310.1%2B20171211jw-alpha

Is this commons/lang3/ArrayUtils a new dependency that should be added to the packaging, or should that ship within VisiCut.jar ?
```
JOB title >square_tri_test_mark+cut.plf< name >square_tri_test_mark+cut.plf< user >visicut<
Layer.dimensions(0: 0.0, 0.0, 214.3252, 145.9484)
ThunderLaser.power(40)
Layer.setSpeed(100000.0)
Layer.setFocus(0.0)
Layer.setFrequency(5000.0)
moveTo(0:164338,000000,95961,200000)
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
	at com.t_oster.liblasercut.drivers.ruida.Lib.absValueToByteArray(Lib.java:131)
	at com.t_oster.liblasercut.drivers.ruida.Layer.moveAbs(Layer.java:321)
	at com.t_oster.liblasercut.drivers.ruida.Layer.vectorTo(Layer.java:156)
	at com.t_oster.liblasercut.drivers.ruida.Ruida.moveTo(Ruida.java:187)
	at com.t_oster.liblasercut.drivers.ThunderLaser.sendJob(ThunderLaser.java:176)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:756)
	at com.t_oster.visicut.gui.MainView$64.run(MainView.java:2219)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.ArrayUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by jnweiger** [comment]
@kkaempf Please assign yourself here :-)

**Comment by mrlinux1** [comment]
I have the same error outside of the Netbeans IDE.

Inside it works ... So I think there is one file missing in the libvisicut library
which is used in the ruida class : ArrayUtils Import missing ?

**Comment by mrlinux1** [comment]
We have to add lib/LibLaserCut/lib/commons-lang3.jar to the libraries of Visicut ;-)

I did that in Netbeans and now it works also outside ;-)

I can create a branch and push it ;-)

**Comment by jnweiger** [comment]
Yes. the trick is to add
```
diff --git a/nbproject/project.properties b/nbproject/project.properties
index b05f686..1ca2270 100644
--- a/nbproject/project.properties
+++ b/nbproject/project.properties
@@ -48,6 +48,7 @@ file.reference.batik-all.jar=lib/kabeja-0.4/lib/batik-all.jar
 file.reference.beansbinding-1.2.1.jar=lib/beansbinding-1.2.1.jar
 file.reference.bridj-0.6.2.jar=lib/bridj-0.6.2.jar
 file.reference.BrowserLoginDialog.jar=lib/BrowserLoginDialog.jar
+file.reference.commons-lang3.jar=lib/commons-lang3.jar
 file.reference.commons-io-2.4.jar=lib/commons-io-2.4.jar
 file.reference.commons-net-3.0.1.jar=lib/commons-net-3.0.1.jar
 file.reference.commons-net-3.1.jar=lib/commons-net-3.1.jar
@@ -107,6 +108,7 @@ javac.classpath=\
     ${file.reference.gtkjfilechooser.jar}:\
     ${file.reference.AppleJavaExtensions.jar}:\
     ${file.reference.commons-net-3.1.jar}:\
+    ${file.reference.commons-lang3.jar}:\
     ${reference.LibLaserCut.jar}:\
     ${file.reference.jna-4.0.0.jar}:\
     ${file.reference.purejavacomm-0.0.22.jar}:\
```
Surprise: nbproject/project.properties is parsed by ant when building the classpath

**Comment by mrlinux1** [comment]
That's, what I described ;-)

**Comment by jnweiger** [comment]
I always thought ant and netbeans were two different things. And I always though dependencies could be transitive. And I always thought the build script would catch a missing dependency. 

All of this seems wrong. I learned something about java today. Yeah :see_no_evil:

**Comment by mrlinux1** [comment]
I can explain that system with Netbeans ;-)

**Comment by jnweiger** [comment]
fixed with https://github.com/fablabnbg/VisiCut/issues/16
Released packages updated inplace https://github.com/fablabnbg/VisiCut/releases/tag/v1.7-310.1%2B20171211jw-alpha
